github.com:
    users:
        al-nf:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: al-nf
